apiVersion: apps/v1
kind: Deployment 
metadata:
  name: devops-app
  labels:
    app: devops-app
spec:
  selector:
    matchLabels:
      app: devops-app
  replicas: 2 
  template:
    metadata:
      labels:
        app: devops-app
    spec:
      containers:
        - name: devops-app
          image: devops
          imagePullPolicy: Always
          ports:
            - containerPort: 2001 


---

apiVersion: v1 
kind: Service 
metadata: 
  name: devops-app
spec:
  selector:
    app: devops-app
  ports:
    - protocol: "TCP"
      port: 2001 
      targetPort: 2001 
  type: NodePort 
